# Generated by Django 3.2.8 on 2021-11-01 02:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Url',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_url', models.URLField(default='', max_length=2100)),
                ('shortend_url', models.URLField(default='', max_length=8)),
                ('create_at', models.DateTimeField(default=datetime.datetime(2021, 11, 1, 11, 20, 22, 121662))),
                ('clicked_count', models.IntegerField(default=0)),
            ],
        ),
    ]
