# Generated by Django 3.2.8 on 2021-11-02 15:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('url', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Response',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result_code', models.IntegerField(default=0)),
                ('result_msg', models.TextField(default='', max_length=1000)),
                ('data', models.JSONField(default=dict)),
            ],
        ),
        migrations.AlterField(
            model_name='url',
            name='create_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 3, 0, 47, 44, 854037)),
        ),
    ]
