# Generated by Django 3.2.8 on 2021-11-02 15:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('url', '0002_auto_20211103_0047'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Response',
        ),
        migrations.AlterField(
            model_name='url',
            name='create_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 3, 0, 49, 56, 309111)),
        ),
    ]
