# Generated by Django 3.2.8 on 2021-11-04 09:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('url', '0003_auto_20211103_0049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='url',
            name='create_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
